const TOPICS=window.CFA_TOPICS, DEFAULT=window.DEFAULT_CARDS;
let cards=JSON.parse(localStorage.getItem('cfa_formula_cards')||'null')||JSON.parse(JSON.stringify(DEFAULT));
cards=cards.map(c=>({...c,subject:c.subject||(c.topic==='Economic Growth'?'Economics':'Unassigned'),topic:c.topic||'General'}));
let librarySubject='All',reviewIds=[],reviewPos=0,extracted=[];
const $=id=>document.getElementById(id);const clean=s=>(s||'').replace(/\s+/g,' ').trim();
const esc=s=>(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const attr=s=>esc(s).replace(/"/g,'&quot;');
const save=()=>localStorage.setItem('cfa_formula_cards',JSON.stringify(cards));
function stats(){const reviewed=cards.filter(c=>c.status),known=cards.filter(c=>c.status==='known'),missed=cards.filter(c=>c.status==='missed');return{reviewed,known,missed,coverage:cards.length?Math.round(reviewed.length/cards.length*100):0,accuracy:reviewed.length?Math.round(known.length/reviewed.length*100):0,mastery:cards.length?Math.round(known.length/cards.length*100):0}}
function refresh(){const s=stats();$('coverage').textContent=s.coverage+'%';$('coverageSmall').textContent=`${s.reviewed.length} of ${cards.length} reviewed`;$('accuracy').textContent=s.accuracy+'%';$('accuracySmall').textContent=`${s.known.length} known · ${s.missed.length} missed`;$('knownCount').textContent=s.known.length;$('missedCount').textContent=s.missed.length;$('accuracyPct').textContent=s.accuracy+'%';$('accuracyBar').style.width=s.accuracy+'%';$('reviewPct').textContent=s.coverage+'%';$('reviewBar').style.width=s.coverage+'%';$('masteryPct').textContent=s.mastery+'%';$('masteryBar').style.width=s.mastery+'%';$('weakList').innerHTML=(s.missed.length?s.missed:cards.filter(c=>!c.status)).slice(0,6).map(c=>`<div class="weak"><span>${esc(c.question)}</span><span class="${c.status==='missed'?'bad':''}">${c.status==='missed'?'×':'•'}</span></div>`).join('');$('subjectOverview').innerHTML=TOPICS.map(t=>{const subset=cards.filter(c=>c.subject===t),rev=subset.filter(c=>c.status).length;return `<div class="subject-mini"><span>${esc(t)}</span><span>${rev}/${subset.length}</span></div>`}).join('');renderLibrary()}
function renderLibrary(){const subjects=['All',...TOPICS];$('topicTabs').innerHTML=subjects.map(t=>{const n=t==='All'?cards.length:cards.filter(c=>c.subject===t).length;return `<button class="topic-chip ${librarySubject===t?'active':''}" data-subject="${attr(t)}">${esc(t)} · ${n}</button>`}).join('');document.querySelectorAll('.topic-chip').forEach(b=>b.onclick=()=>{librarySubject=b.dataset.subject;renderLibrary()});const visible=librarySubject==='All'?cards:cards.filter(c=>c.subject===librarySubject);$('formulaCountPill').textContent=`${visible.length} formula${visible.length===1?'':'s'}`;if(!visible.length){$('libraryContent').innerHTML=`<div class="empty">No formulas in <strong>${esc(librarySubject)}</strong> yet. Use Upload chapter to add some.</div>`;return}const groups={};visible.forEach(c=>{groups[c.subject]??={};groups[c.subject][c.topic]??=[];groups[c.subject][c.topic].push(c)});let html='';Object.keys(groups).sort((a,b)=>TOPICS.indexOf(a)-TOPICS.indexOf(b)).forEach(subject=>Object.keys(groups[subject]).sort().forEach(topic=>{const g=groups[subject][topic];html+=`<div class="library-group"><div class="library-head"><div><div class="library-title">${esc(subject)}</div><div class="library-meta">${esc(topic)}</div></div><div class="library-meta">${g.length} formula${g.length===1?'':'s'}</div></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Prompt</th><th>Formula</th><th>Status</th></tr></thead><tbody>${g.map(c=>{const label=c.status==='known'?'Known':c.status==='missed'?'Missed':'Unreviewed';return `<tr><td>${c.id}</td><td>${esc(c.question)}</td><td><code>${esc(c.answer)}</code></td><td><span class="status-dot ${c.status||''}"></span>${label}</td></tr>`}).join('')}</tbody></table></div></div>`}));$('libraryContent').innerHTML=html}
function showView(name){['dashboard','review','formulas','upload'].forEach(v=>$(v+'View').style.display=v===name?'block':'none');document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='review'&&!reviewIds.length)startReview();if(name==='formulas')renderLibrary()}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
function startReview(){const missed=cards.filter(c=>c.status==='missed').map(c=>c.id);reviewIds=missed.length?missed:cards.map(c=>c.id);reviewPos=0;renderReview();showView('review')}
function renderReview(){if(!reviewIds.length)return;const c=cards.find(x=>x.id===reviewIds[reviewPos]);$('question').textContent=c.question;$('answer').textContent=c.answer;$('answer').style.display='none';$('reviewCounter').textContent=`${reviewPos+1} / ${reviewIds.length}`}
function rate(status){const c=cards.find(x=>x.id===reviewIds[reviewPos]);if(!c)return;c.status=status;save();refresh();if(reviewIds.length>1)reviewPos=(reviewPos+1)%reviewIds.length;renderReview()}
$('startReview').onclick=startReview;$('reveal').onclick=()=>$('answer').style.display='block';$('prevBtn').onclick=()=>{reviewPos=(reviewPos-1+reviewIds.length)%reviewIds.length;renderReview()};$('nextBtn').onclick=()=>{reviewPos=(reviewPos+1)%reviewIds.length;renderReview()};$('markWrong').onclick=()=>rate('missed');$('markKnown').onclick=()=>rate('known');$('resetDemo').onclick=()=>{localStorage.removeItem('cfa_formula_cards');cards=JSON.parse(JSON.stringify(DEFAULT));librarySubject='All';reviewIds=[];reviewPos=0;save();refresh()};
$('uploadSubject').innerHTML=TOPICS.map(t=>`<option ${t==='Economics'?'selected':''}>${esc(t)}</option>`).join('');
function norm(s){return(s||'').toLowerCase().replace(/[−–—]/g,'-').replace(/\s+/g,'').replace(/[;,.]+$/g,'')}
function likely(line){const t=clean(line);if(t.length<4||t.length>220||!t.includes('='))return false;const math=(t.match(/[+\-−×÷*/^()\[\]αβγδθλμσρΨ∆Δ]/g)||[]).length;return(math>0||/\b(g|r|y|k|p|e|var|cov|eps|roe|wacc|fcf|npv|irr)\b/i.test(t))&&t.split(/\s+/).length<30}
function label(prev,page){const p=clean(prev);return p&&!likely(p)&&p.length<=110&&!/^\d+$/.test(p)?p.replace(/[:.]+$/,'')+' — formula?':`Formula from page ${page}?`}
async function pdfExtract(file){if(!window.pdfjsLib)throw Error('PDF extractor did not load. Refresh and try again.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,out=[];for(let p=1;p<=pdf.numPages;p++){$('uploadStatus').textContent=`Scanning PDF page ${p} of ${pdf.numPages}…`;const page=await pdf.getPage(p),tc=await page.getTextContent(),rows={};tc.items.forEach(it=>{const y=Math.round(it.transform[5]);(rows[y]??=[]).push({x:it.transform[4],s:it.str})});const lines=Object.keys(rows).map(Number).sort((a,b)=>b-a).map(y=>rows[y].sort((a,b)=>a.x-b.x).map(o=>o.s).join(' ')).map(clean).filter(Boolean);for(let i=0;i<lines.length;i++)if(likely(lines[i]))out.push({front:label(lines[i-1],p),back:lines[i],selected:true})}return out}
async function textExtract(file){const lines=(await file.text()).split(/\r?\n/).map(clean).filter(Boolean);return lines.map((l,i)=>likely(l)?{front:label(lines[i-1],1),back:l,selected:true}:null).filter(Boolean)}
async function jsonExtract(file){const obj=JSON.parse(await file.text()),arr=Array.isArray(obj)?obj:(obj.cards||obj.formulas||[]);return arr.map((x,i)=>({front:clean(x.front||x.question||x.name||`Imported formula ${i+1}?`),back:clean(x.back||x.answer||x.formula||''),selected:true})).filter(x=>x.back)}
function markDup(list){const existing=new Set(cards.map(c=>norm(c.answer)));return list.map(x=>({...x,duplicate:existing.has(norm(x.back))}))}
function renderExtracted(){const box=$('extractList');$('previewCard').style.display=extracted.length?'block':'none';$('selectAllBtn').disabled=!extracted.length;$('addExtractedBtn').disabled=!extracted.length;box.innerHTML=extracted.map((c,i)=>`<div class="extract-item"><div><input type="checkbox" class="xcheck" data-i="${i}" ${c.selected?'checked':''}></div><div class="fields"><input type="text" class="xfront" data-i="${i}" value="${attr(c.front)}"><textarea class="xback" data-i="${i}">${esc(c.back)}</textarea>${c.duplicate?'<div class="duplicate">Possible duplicate already in your deck.</div>':''}</div></div>`).join('');document.querySelectorAll('.xcheck').forEach(e=>e.onchange=()=>extracted[+e.dataset.i].selected=e.checked);document.querySelectorAll('.xfront').forEach(e=>e.oninput=()=>extracted[+e.dataset.i].front=e.value);document.querySelectorAll('.xback').forEach(e=>e.oninput=()=>extracted[+e.dataset.i].back=e.value)}
$('extractBtn').onclick=async()=>{const file=$('uploadFile').files[0];if(!file){$('uploadStatus').textContent='Please choose a PDF, TXT or JSON file first.';return}try{$('extractBtn').disabled=true;$('uploadStatus').textContent='Reading file…';const n=file.name.toLowerCase();let found=n.endsWith('.pdf')?await pdfExtract(file):n.endsWith('.json')?await jsonExtract(file):await textExtract(file);const seen=new Set();found=found.filter(x=>{const k=norm(x.back);if(!k||seen.has(k))return false;seen.add(k);return true});extracted=markDup(found);renderExtracted();const d=extracted.filter(x=>x.duplicate).length;$('uploadStatus').textContent=`Found ${extracted.length} formula candidate${extracted.length===1?'':'s'}${d?` · ${d} possible duplicate${d===1?'':'s'}`:''}. Review before adding.`}catch(e){$('uploadStatus').textContent='Could not extract formulas: '+e.message}finally{$('extractBtn').disabled=false}};
$('selectAllBtn').onclick=()=>{const all=extracted.length&&extracted.every(x=>x.selected);extracted.forEach(x=>x.selected=!all);renderExtracted()};
$('addExtractedBtn').onclick=()=>{const subject=clean($('uploadSubject').value),topic=clean($('uploadTopic').value);if(!topic){$('uploadStatus').textContent='Please enter a chapter / subtopic before adding formulas.';return}const existing=new Set(cards.map(c=>norm(c.answer)));let next=cards.reduce((m,c)=>Math.max(m,+c.id||0),0)+1,added=0,skipped=0;extracted.filter(x=>x.selected).forEach(x=>{const n=norm(x.back);if(!n||existing.has(n)){skipped++;return}cards.push({id:next++,question:clean(x.front)||'Recall the formula?',answer:clean(x.back),subject,topic,status:null});existing.add(n);added++});save();refresh();$('uploadStatus').textContent=`Added ${added} formula${added===1?'':'s'} to ${subject} → ${topic}.${skipped?` Skipped ${skipped} duplicate${skipped===1?'':'s'}.`:''}`;extracted=markDup(extracted);renderExtracted()};
save();refresh();showView('dashboard');