window.CFA_TOPICS=['Quantitative Methods','Economics','Financial Statement Analysis','Corporate Issuers','Equity Valuation','Fixed Income','Derivatives','Alternative Investments','Portfolio Management'];
window.DEFAULT_CARDS=[
{id:1,question:'Grinold–Kroner Expected Equity Return',answer:'E(Re) = dy + Δ(P/E) + i + g − ΔS',latex:'E(R_e)=dy+\\Delta(P/E)+i+g-\\Delta S',subject:'Economics',topic:'Economic Growth',status:null},
{id:2,question:'Grinold–Kroner — EPS Growth',answer:'EPS growth = i + g − ΔS',latex:'\\text{EPS growth}=i+g-\\Delta S',subject:'Economics',topic:'Economic Growth',status:null},
{id:3,question:'Change in Shares Outstanding',answer:'ΔS = RD − NBB',latex:'\\Delta S=\\mathrm{RD}-\\mathrm{NBB}',subject:'Economics',topic:'Economic Growth',status:null},
{id:4,question:'Cobb–Douglas Production Function',answer:'Y = A K^α L^(1−α)',latex:'Y=AK^{\\alpha}L^{1-\\alpha}',subject:'Economics',topic:'Economic Growth',status:null},
{id:5,question:'Marginal Product of Capital (MPK)',answer:'MPK = α(Y/K) = r',latex:'\\mathrm{MPK}=\\alpha\\left(\\frac{Y}{K}\\right)=r',subject:'Economics',topic:'Economic Growth',status:null},
{id:6,question:'Marginal Product of Labor (MPL)',answer:'MPL = (1−α)(Y/L) = w',latex:'\\mathrm{MPL}=(1-\\alpha)\\left(\\frac{Y}{L}\\right)=w',subject:'Economics',topic:'Economic Growth',status:null},
{id:7,question:'Capital and Labor Income Shares',answer:'α = rK/Y ; 1−α = wL/Y',latex:'\\alpha=\\frac{rK}{Y},\\qquad 1-\\alpha=\\frac{wL}{Y}',subject:'Economics',topic:'Economic Growth',status:null},
{id:8,question:'Cobb–Douglas — Output per Worker',answer:'y = Y/L = A k^α, where k = K/L',latex:'y=\\frac{Y}{L}=Ak^{\\alpha},\\qquad k=\\frac{K}{L}',subject:'Economics',topic:'Economic Growth',status:null},
{id:9,question:'Growth Accounting Equation',answer:'gY = gA + αgK + (1−α)gL',latex:'g_Y=g_A+\\alpha g_K+(1-\\alpha)g_L',subject:'Economics',topic:'Economic Growth',status:null},
{id:10,question:'Potential GDP Growth',answer:'gPotential GDP = gLabor Force + gLabor Productivity',latex:'g_{\\text{Potential GDP}}=g_{\\text{Labor Force}}+g_{\\text{Labor Productivity}}',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:11,question:'Aggregate Capital Growth',answer:'gK = s(Y/K) − δ',latex:'g_K=s\\left(\\frac{Y}{K}\\right)-\\delta',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:12,question:'Capital per Worker Growth — Link to Aggregate Capital',answer:'gk = gK − n',latex:'g_k=g_K-n',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:13,question:'Capital per Worker Growth — Expanded',answer:'gk = s(Y/K) − δ − n',latex:'g_k=s\\left(\\frac{Y}{K}\\right)-\\delta-n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:14,question:'Output per Worker Growth',answer:'gy = θ + αgk',latex:'g_y=\\theta+\\alpha g_k',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:15,question:'Output per Worker Growth — Expanded',answer:'gy = θ + α[s(Y/K) − δ − n]',latex:'g_y=\\theta+\\alpha\\left[s\\left(\\frac{Y}{K}\\right)-\\delta-n\\right]',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:16,question:'Steady-State Growth per Worker',answer:'g* = θ/(1−α)',latex:'g^{*}=\\frac{\\theta}{1-\\alpha}',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:17,question:'Steady-State Required Investment per Worker',answer:'[δ + n + θ/(1−α)]k',latex:'\\left[\\delta+n+\\frac{\\theta}{1-\\alpha}\\right]k',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:18,question:'Steady-State Threshold Ratio (Ψ)',answer:'Ψ = [δ + n + θ/(1−α)] / s',latex:'\\Psi=\\frac{\\delta+n+\\frac{\\theta}{1-\\alpha}}{s}',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:19,question:'Steady-State Capital–Output Ratio',answer:'Ψ = (Y/K)*',latex:'\\Psi=\\left(\\frac{Y}{K}\\right)^{*}',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:20,question:'Convergence — Capital per Worker Growth',answer:'gk = θ/(1−α) + s[(Y/K)−Ψ]',latex:'g_k=\\frac{\\theta}{1-\\alpha}+s\\left[\\left(\\frac{Y}{K}\\right)-\\Psi\\right]',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:21,question:'Convergence — Output per Worker Growth',answer:'gy = θ/(1−α) + αs[(Y/K)−Ψ]',latex:'g_y=\\frac{\\theta}{1-\\alpha}+\\alpha s\\left[\\left(\\frac{Y}{K}\\right)-\\Psi\\right]',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:22,question:'Steady-State Per-Worker Growth',answer:'gk* = gy* = θ/(1−α)',latex:'g_k^{*}=g_y^{*}=\\frac{\\theta}{1-\\alpha}',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:23,question:'Aggregate vs Per-Worker Capital Growth',answer:'gK = gk + n',latex:'g_K=g_k+n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:24,question:'Aggregate vs Per-Worker Output Growth',answer:'gY = gy + n',latex:'g_Y=g_y+n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:25,question:'Steady-State Aggregate Growth',answer:'gK* = gY* = n + θ/(1−α)',latex:'g_K^{*}=g_Y^{*}=n+\\frac{\\theta}{1-\\alpha}',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:26,question:'No Technological Progress — Per-Worker Growth',answer:'gk = gy = 0',latex:'g_k=g_y=0',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:27,question:'No Technological Progress — Aggregate Growth',answer:'gK = gY = gL = n',latex:'g_K=g_Y=g_L=n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:28,question:'Endogenous Growth — Capital per Worker',answer:'gk = sc − δ − n',latex:'g_k=sc-\\delta-n',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:29,question:'Endogenous Growth — Output per Worker',answer:'gy = gk = sc − δ − n',latex:'g_y=g_k=sc-\\delta-n',subject:'Economics',topic:'Economic Growth',status:'missed'}
];