window.CFA_TOPICS=['Quantitative Methods','Economics','Financial Statement Analysis','Corporate Issuers','Equity Valuation','Fixed Income','Derivatives','Alternative Investments','Portfolio Management'];
window.DEFAULT_CARDS=[
{id:1,question:'What is the Grinold–Kroner expected equity return formula?',answer:'E(Re) = dy + Δ(P/E) + i + g − ΔS',subject:'Economics',topic:'Economic Growth',status:null},
{id:2,question:'How is EPS growth expressed in Grinold–Kroner?',answer:'EPS growth = i + g − ΔS',subject:'Economics',topic:'Economic Growth',status:null},
{id:3,question:'Formula for change in shares outstanding?',answer:'ΔS = RD − NBB',subject:'Economics',topic:'Economic Growth',status:null},
{id:4,question:'What is the Cobb–Douglas production function?',answer:'Y = A K^α L^(1−α)',subject:'Economics',topic:'Economic Growth',status:null},
{id:5,question:'Formula for marginal product of capital (MPK)?',answer:'MPK = α(Y/K) = r',subject:'Economics',topic:'Economic Growth',status:null},
{id:6,question:'Formula for marginal product of labor (MPL)?',answer:'MPL = (1−α)(Y/L) = w',subject:'Economics',topic:'Economic Growth',status:null},
{id:7,question:'Formulas for capital and labor income shares?',answer:'α = rK/Y ; 1−α = wL/Y',subject:'Economics',topic:'Economic Growth',status:null},
{id:8,question:'What is output per worker in Cobb–Douglas?',answer:'y = Y/L = A k^α, where k = K/L',subject:'Economics',topic:'Economic Growth',status:null},
{id:9,question:'What is the growth accounting equation?',answer:'gY = gA + αgK + (1−α)gL',subject:'Economics',topic:'Economic Growth',status:null},
{id:10,question:'Formula for potential GDP growth?',answer:'gPotential GDP = gLabor Force + gLabor Productivity',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:11,question:'Formula for aggregate capital growth, gK?',answer:'gK = s(Y/K) − δ',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:12,question:'Formula linking capital-per-worker growth to gK?',answer:'gk = gK − n',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:13,question:'Formula for gk using Y/K?',answer:'gk = s(Y/K) − δ − n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:14,question:'Formula for output-per-worker growth, gy?',answer:'gy = θ + αgk',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:15,question:'Expanded formula for gy?',answer:'gy = θ + α[s(Y/K) − δ − n]',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:16,question:'Steady-state growth rate per worker?',answer:'g* = θ/(1−α)',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:17,question:'Required investment per worker at steady state?',answer:'[δ + n + θ/(1−α)]k',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:18,question:'Formula for Ψ?',answer:'Ψ = [δ + n + θ/(1−α)] / s',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:19,question:'At steady state, Ψ equals what ratio?',answer:'Ψ = (Y/K)*',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:20,question:'Convergence formula for gk?',answer:'gk = θ/(1−α) + s[(Y/K)−Ψ]',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:21,question:'Convergence formula for gy?',answer:'gy = θ/(1−α) + αs[(Y/K)−Ψ]',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:22,question:'Steady-state gk and gy?',answer:'gk* = gy* = θ/(1−α)',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:23,question:'Formula linking aggregate and per-worker capital growth?',answer:'gK = gk + n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:24,question:'Formula linking aggregate and per-worker output growth?',answer:'gY = gy + n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:25,question:'Steady-state aggregate growth rate?',answer:'gK* = gY* = n + θ/(1−α)',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:26,question:'If θ = 0, what are gk and gy?',answer:'gk = gy = 0',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:27,question:'If θ = 0, what are gK, gY, and gL?',answer:'gK = gY = gL = n',subject:'Economics',topic:'Economic Growth',status:'missed'},
{id:28,question:'Endogenous growth formula for gk?',answer:'gk = sc − δ − n',subject:'Economics',topic:'Economic Growth',status:'known'},
{id:29,question:'Endogenous growth formula for gy?',answer:'gy = gk = sc − δ − n',subject:'Economics',topic:'Economic Growth',status:'missed'}
];